#site_name: Docs with mkdocs
#site_url: https://my-site.com
#
#nav:
#    - Home: index.md
#    - About: about.md
#    - 'Guide':
#        - 'Settings': setup.md
#
#theme:
#    name: dracula
#    language: vi
#    features:
#      - navigation.tabs

site_name: MkDocs
site_url: https://www.mkdocs.org/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/mkdocs/mkdocs/
edit_uri: blob/master/docs/

theme:
  name: dracula
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  logo: assets/img/dracula.png
  favicon: assets/favicon.ico

nav:
  - Home: index.md
  - Portfolio: portfolio.md
#  - Getting Started: getting-started.md
#  - User Guide: user-guide/
#  - Developer Guide: dev-guide/
  - Repositories:
    - Перый семестр: lab_idx_1_sem.md
    - Второй семестр: lab_idx_2_sem.md
  - О сайте:
    - Кодекс поведения: about/code_of_conduct.md
    - Contributing: about/contributing.md
    - License: about/license.md

extra_css:
  - css/extra.css

exclude_docs: |
  *.py

markdown_extensions:
  - toc:
      permalink:
  - attr_list
  - def_list
  - tables

copyright: Copyright &copy; 2014 <a href="https://twitter.com/starletdreaming">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.

plugins:
  - search
